### ISSUE TITLE
Problem in GlyphIndexList.Replace()

### ISSUE THREAD

**Issue by samhocevar** [LayoutFarm/Typography#80]
At line `114` in `GlyphIndexList.cs`, `_tmpGlypIndexBackup` may be empty if the whole string was replaced with a ligature, so the code crashes there when accessing `_tmpGlypIndexBackup[0]`.

I might be able to fix this later, but I do not really understand `GlyphIndexToUserChar` yet. Maybe you know what’s going on and can fix it more quickly than me :-)

**Comment by prepare** [comment]
Thank you,
 fixed, see => https://github.com/LayoutFarm/Typography/commit/07352697dade7b89a414004eb1e3040ec36427e3

---

Disable Ligature and Enable Ligature, Palatino Font
---



![fi_1](https://user-images.githubusercontent.com/7447159/32790322-b6b2dbea-c990-11e7-9578-f468fdcb03a4.png)

_pic 1: f-i Disable Ligature_

---

![fi_2](https://user-images.githubusercontent.com/7447159/32790324-b73dde66-c990-11e7-8d58-380eeb8508ee.png)

_pic 2: f-i Enable Ligature_

**Comment by prepare** [comment]
@samhocevar 

when we do glyph substitution,
user input chars may not be mapped with output rendered glyph index 1:1. (see _pic2_ above)

so `GlyphIndexToUserChar` and related structures
are needed to store that mapping when developing a 'textbox' control.

**Comment by samhocevar** [comment]
It looks like there is still a problem; see:

1. List is emptied

            _tmpGlypIndexBackup.Clear();

2. `removeLen` elements are added starting from **0**:

            int endAt = index + removeLen;
            for (int i = index; i < endAt; ++i)
            {
                _tmpGlypIndexBackup.Add(_mapGlyphIndexToUserChar[i]);
            }

3. `removeLen` elements are removed starting from **index**:

            _tmpGlypIndexBackup.RemoveRange(index, removeLen);

**Comment by prepare** [comment]
@samhocevar,

 
`removeLen` must >=1 right ?

if so  then `_tmpGlypIndexBackup.Count` must > 0

since collection count > 0
we pick the 1st glyph index before  call `RemoveRange()`

_tmpGlypIndexBackup[0] should not crash.

from https://github.com/LayoutFarm/Typography/commit/07352697dade7b89a414004eb1e3040ec36427e3

**Comment by prepare** [comment]
@samhocevar ,

I see ! 


:)

see=> https://github.com/LayoutFarm/Typography/commit/776257eeabb36c9fc61826858aabe5ed920b1ce6

**Comment by prepare** [comment]
![replace1](https://user-images.githubusercontent.com/7447159/32890983-87624366-cb03-11e7-9bd4-5356e1e4a593.png)

**Comment by samhocevar** [comment]
OK! But then, is `_tmpGlypIndexBackup` really needed? We only take the first element, then it is emptied again 🤔

**Comment by prepare** [comment]
actually, not need.
I use it during debug.

see =>https://github.com/LayoutFarm/Typography/commit/b98126370ed7dc1e1ae430694fd7e247737b6741

**Comment by prepare** [comment]
Palatino Linotype
--- 

![replace_4](https://user-images.githubusercontent.com/7447159/32897031-1f4f35d6-cb17-11e7-80e3-387c3f677623.png)
